name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Installer Node 22
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4️⃣ Builder le projet Vite
      - name: Build project
        run: npm run build

      # 5️⃣ Copier index.html en 404.html pour React Router
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      # 6️⃣ Upload du build pour le déploiement
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # 1️⃣ Télécharger l’artefact build
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # 2️⃣ Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PAT }}
          publish_dir: ./dist
